### ISSUE TITLE
Transfer repository to chnm organization

### ISSUE THREAD

**Issue by lmullen** [chnm/relec-website#51]
Over time we want to move all active projects to the `chnm` organization.

**Comment by hepplerj** [comment]
This seems like something Github can [handle pretty easily](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository) for us.

**Comment by lmullen** [comment]
@hepplerj Should I just go ahead and do this?

**Comment by hepplerj** [comment]
Is the plan to move all of the existing repositories over from the `religious-ecologies` org? You may want to double check nothing conflicts with existing repos in the `chnm` org. I'd imagine Github does this check anyway? But the docs don't seem to mention anything about that, so I'm not sure if that means we need to do any renaming before we initiate the transfer or not. Plus we may want to rename a few of the repos just so it's clear what's in them (so, e.g., `website` might become `relcol-website` so we don't get confusion down the line that `website` isn't the CHNM website 😄 ). 

Otherwise, if Github can handle the transfer easily enough for us, I don't see why not just go ahead? (That said, I've never had to move repos to a new org before and I'm not sure what the process is like. Happy to help troubleshoot/test/press buttons.)

**Comment by lmullen** [comment]
I have unfortunately moved lots of repositories. 🥲 It's not that hard, and actually GitHub has really good redirection so pulls/pushes etc should continue to work on the clients without any effort. 

Yes, I think that over time we want all repositories at RRCHNM in the `chnm` team, so we can better manage permissions, know what we have, etc.

The other repositories in this organization are related to the Omeka S site, so I think it would be better if God's Will moved them at his convenience.

I'll start moving this one over.

**Comment by lmullen** [comment]
This was in fact moved.
